### ISSUE TITLE
你的RBTree不是平衡的

### ISSUE THREAD

**Issue by emojihao** [liuyubobobo/Play-with-Data-Structures#11]
你的RBTree不是平衡的。

**Comment by liuyubobobo** [comment]
课程中介绍的RBTree是LLRB左倾红黑树。参考第十三章10小节的说明。这种红黑树本身就不是严格平衡的，课程中也有介绍。但是高度是O(logn)级别的。（严格来说是2logn的）。

**Comment by emojihao** [comment]
不好意思。
