### ISSUE TITLE
heapify 有点小问题

### ISSUE THREAD

**Issue by dyq666** [liuyubobobo/Play-with-Data-Structures#13]
https://github.com/liuyubobobo/Play-with-Data-Structures/blob/master/08-Heap-and-Priority-Queue/05-Heapify-and-Replace-in-Heap/src/MaxHeap.java#L13-L17

```java
    public MaxHeap(E[] arr){
        data = new Array<>(arr);
        for(int i = parent(arr.length - 1) ; i >= 0 ; i --)
            siftDown(i);
    }
```

当 `arr.length == 1` 时, `parent` 会报错, 但实际上应该是支持将一个元素的数组变为最大堆.

**Comment by liuyubobobo** [comment]
你是正确的。感谢。当 arr.length == 1 的时候，可以不应该执行 heapify 的过程了，因为自己已经是一个堆了。源代码已经进行了修改：）
