### ISSUE TITLE
一个字母拼错了

### ISSUE THREAD

**Issue by zchengi** [liuyubobobo/Play-with-Data-Structures#5]
https://github.com/liuyubobobo/Play-with-Data-Structures/blob/6419bec9a30214f24a61c35fb3f7973574bce3b5/05-Recursion/Optional-01-Recursive-LinkedList/src/LinkedListR.java#L4

>  Resursion -> Recursion

**Comment by liuyubobobo** [comment]
谢谢提醒，在下一个版本更新时会修复：）

**Comment by zchengi** [comment]
https://github.com/liuyubobobo/Play-with-Data-Structures/blob/6419bec9a30214f24a61c35fb3f7973574bce3b5/05-Recursion/Optional-01-Recursive-LinkedList/src/LinkedListR.java#L149-L155

- 在我测试  `removeLast()` 时报错 `NullPointerException`；
- debug 后发现在153、154行逻辑出现错误，每次递归返回 Pair 的 key 是已删除节点的下一个节点，而这里预期应该返回链表头节点；
- 这是我修改后的代码：
```
    private Pair<Node, E> remove(Node node, int index) {
        if (index == 0) {
            return new Pair<>(node.next, node.e);
        }

        Pair<Node, E> res = remove(node.next, index - 1);
        node.next = res.getKey();
        return new Pair<>(node, res.getValue());
    }
```
- 虽然实现了递归删除的方法，但是代码上看起来很繁琐，不够简洁，暂时没想到其他优化的方法。

**Comment by liuyubobobo** [comment]
你是对的。我已经进行了update。谢谢你！：）
