### ISSUE TITLE
Python implementation:)

### ISSUE THREAD

**Issue by nicemayi** [liuyubobobo/Play-with-Data-Structures#7]
bobo老师您好！

最近将您《玩转数据结构》这门课又过了一遍，同时重新将您这门课上绝大部分内容用python实现了一遍（[link](https://github.com/nicemayi/play-with-data-structures)），欢迎fork/pr或者link到您这门课的repo里，期待能让更多以python为主力语言的同学更好的学习您这门课。

谢谢您提供了这么高质量的算法课程，同时也期待您下一门课：）

**Comment by liuyubobobo** [comment]
是购买课程的同学吗？如果是的话，请通过课程qq群和我联系一下，我可以在课程中，包括课程qq群中给你宣传一下。

**Comment by nicemayi** [comment]
是的呀：）您慕课上所有的课程我都买过了！当时对我跳槽帮助太大了！不好意思好没有注意到课程的qq群，现在去加一下:)

**Comment by liuyubobobo** [comment]
大赞！谢谢你的支持：）在慕课网web端课程章节列表右侧应该有群信息。加一下：）

**Comment by liuyubobobo** [comment]
简单看了一下代码，非常赞！

**Comment by nicemayi** [comment]
谢谢bobo老师赞赏~今晚和明天准备过完最后一章hash，代码就齐全了：）
下周打算再过一遍《算法与数据结构》和《玩转算法面试》，也在准备用python重写一遍。

这么做的目的主要是我发现现在越来越多的朋友都在用python刷题准备面试，希望能为用python找工作的朋友点帮助，也能给自己加点人品:)
